CREATE TABLE Characters_TC (
    id INT(3) NOT NULL AUTO_INCREMENT,
    name VARCHAR(30) NOT NULL,
    label VARCHAR(10) NOT NULL,
    game VARCHAR(4) NOT NULL,
    last_updated INT(11) NOT NULL,
    PRIMARY KEY(id)
) CHARACTER SET utf8mb4;